services:
  - type: web
    name: egox
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn server:app --bind 0.0.0.0:$PORT
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.4
      - key: FF_BOT_TOKEN
        sync: false
      - key: API_BASE
        sync: false
      - key: SERVERS
        value: IND4
