# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: PlayerCSStats.proto
# Protobuf Python Version: 6.33.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    1,
    '',
    'PlayerCSStats.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13PlayerCSStats.proto\x12\rPlayerCSStats\"S\n\x07request\x12\x11\n\taccountid\x18\x01 \x01(\x04\x12\x10\n\x08seasonid\x18\x02 \x01(\r\x12\x10\n\x08gamemode\x18\x03 \x01(\r\x12\x11\n\tmatchmode\x18\x04 \x01(\r\"B\n\x08response\x12\x36\n\x07\x63sstats\x18\x01 \x01(\x0b\x32%.PlayerCSStats.AccountInfoWithTCStats\"\x94\x01\n\x16\x41\x63\x63ountInfoWithTCStats\x12\x11\n\taccountid\x18\x01 \x01(\x04\x12\x13\n\x0bgamesplayed\x18\x02 \x01(\r\x12\x0c\n\x04wins\x18\x03 \x01(\r\x12\r\n\x05kills\x18\x04 \x01(\r\x12\x35\n\rdetailedstats\x18\x05 \x01(\x0b\x32\x1e.PlayerCSStats.DetailedTCStats\"\xcf\x03\n\x0f\x44\x65tailedTCStats\x12\x11\n\tmvp_count\x18\x01 \x01(\r\x12\x14\n\x0c\x64ouble_kills\x18\x02 \x01(\r\x12\x14\n\x0ctriple_kills\x18\x03 \x01(\r\x12\x12\n\nfour_kills\x18\x04 \x01(\r\x12\x0e\n\x06\x64\x61mage\x18\x05 \x01(\r\x12\x17\n\x0fhead_shot_kills\x18\x06 \x01(\r\x12\x13\n\x0bknock_downs\x18\x07 \x01(\r\x12\x10\n\x08revivals\x18\x08 \x01(\r\x12\x0f\n\x07\x61ssists\x18\t \x01(\r\x12\x0e\n\x06\x64\x65\x61ths\x18\n \x01(\r\x12\x13\n\x0bstreak_wins\x18\x0b \x01(\r\x12\x16\n\x0ethrowing_kills\x18\x0c \x01(\r\x12\x1c\n\x14one_game_most_damage\x18\r \x01(\r\x12\x1b\n\x13one_game_most_kills\x18\x0e \x01(\r\x12\x15\n\rrating_points\x18\x0f \x01(\x01\x12\x1c\n\x14rating_enabled_games\x18\x10 \x01(\r\x12\x16\n\x0eheadshot_count\x18\x11 \x01(\r\x12\x11\n\thit_count\x18\x12 \x01(\r\x12\x16\n\x0egold_medal_cnt\x18\x13 \x01(\r\x12\x18\n\x10silver_medal_cnt\x18\x14 \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'PlayerCSStats_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REQUEST']._serialized_start=38
  _globals['_REQUEST']._serialized_end=121
  _globals['_RESPONSE']._serialized_start=123
  _globals['_RESPONSE']._serialized_end=189
  _globals['_ACCOUNTINFOWITHTCSTATS']._serialized_start=192
  _globals['_ACCOUNTINFOWITHTCSTATS']._serialized_end=340
  _globals['_DETAILEDTCSTATS']._serialized_start=343
  _globals['_DETAILEDTCSTATS']._serialized_end=806
# @@protoc_insertion_point(module_scope)
